###
@baseUrl = https://localhost:4000
@postId = 6523f2cb8f35b5d7c8d1a382
###
POST https://localhost:4000/api/user/ HTTP/1.1
Content-Type: application/json

{
    "username": "newuser2",
    "password": "password1234",
    "firstName": "John"
}
###
POST https://localhost:4000/api/auth/ HTTP/1.1
Content-Type: application/json

{
    "username": "newuser",
    "password": "password123"
}
###
GET https://localhost:3000/api/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhY2JiZjE1NTJkNzY0NWZjNjZmNjEiLCJpYXQiOjE2OTY4NTM5MzR9.CpsHlB2gNhFKCEEVuny3hZJNXH6ruDbX9FAbIpo3Lgs
###
POST https://localhost:4000/api/posts/ HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhY2JiZjE1NTJkNzY0NWZjNjZmNjEiLCJpYXQiOjE2OTY4NTM5MzR9.CpsHlB2gNhFKCEEVuny3hZJNXH6ruDbX9FAbIpo3Lgs

{
    "title": "New world",
    "description": "Testing a new world",
    "departmentCode": "World123"
}
###
GET https://localhost:4000/api/posts HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhY2JiZjE1NTJkNzY0NWZjNjZmNjEiLCJpYXQiOjE2OTY4NTM5MzR9.CpsHlB2gNhFKCEEVuny3hZJNXH6ruDbX9FAbIpo3Lgs
###
DELETE {{baseUrl}}/api/posts/{{postId}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFhY2JiZjE1NTJkNzY0NWZjNjZmNjEiLCJpYXQiOjE2OTY4NTM5MzR9.CpsHlB2gNhFKCEEVuny3hZJNXH6ruDbX9FAbIpo3Lgs
###